# Generated by Django 5.2.5 on 2025-08-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='buy_in_cents',
        ),
        migrations.AddField(
            model_name='season',
            name='buy_in_dollars',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
